name: Deploy to ECR

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install npm and test
        run: |
          npm install
          npm test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Continue if branch is not master
        uses: actions/bin/filter@25b7b846d5027eac3315b50a8055ea675e2abd89
        with:
          args: branch master

      - uses: actions/checkout@v1

      - run: echo hello
        if: github.ref != 'refs/head/master'

      - name: Login to ECR
        uses: actions/aws/cli@efb074ae4510f2d12c7801e4461b65bf5e8317e6
        with:
          args: ecr get-login --no-include-email --region $AWS_DEFAULT_REGION | sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build docker image
        uses: actions/docker/cli@fe7ed3ce992160973df86480b83a2f8ed581cd50
        with:
          args: build -t american-shorthair .

      - name: Tag docker image
        uses: actions/docker/tag@fe7ed3ce992160973df86480b83a2f8ed581cd50
        with:
          args: $IMAGE_NAME $CONTAINER_REGISTRY_PATH/$IMAGE_NAME
        env:
          CONTAINER_REGISTRY_PATH: ${{ secrets.CONTAINER_REGISTRY_PATH }}
          IMAGE_NAME: american-shorthair


      - name: Push image to ECR
        uses: actions/docker/cli@fe7ed3ce992160973df86480b83a2f8ed581cd50
        with:
          args: push $CONTAINER_REGISTRY_PATH/$IMAGE_NAME
        env:
          CONTAINER_REGISTRY_PATH: ${{ secrets.CONTAINER_REGISTRY_PATH }}
          IMAGE_NAME: american-shorthair
