on: push
name: Build and Deploy
jobs:
  loginToECR:
    name: Login to ECR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to ECR
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ap-northeast-2
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: ecr get-login --no-include-email --region $AWS_DEFAULT_REGION | sh
    - name: Docker build
      uses: actions/docker/cli@master
      with:
        args: build -t american-shorthair .
    - name: Push image to ECR
      uses: actions/docker/cli@master
      env:
        CONTAINER_REGISTRY_PATH: ${{ secrets.CONTAINER_REGISTRY_PATH }}
        IMAGE_NAME: american-shorthair
      with:
        args: push $CONTAINER_REGISTRY_PATH/$IMAGE_NAME
    - name: Docker Tag
      uses: actions/docker/tag@fe7ed3ce992160973df86480b83a2f8ed581cd50
      env:
        CONTAINER_REGISTRY_PATH: ${{ secrets.CONTAINER_REGISTRY_PATH }}
        IMAGE_NAME: american-shorthair
      with:
        args: $IMAGE_NAME $CONTAINER_REGISTRY_PATH/$IMAGE_NAME
