name: Test codes

on:
  push:
    branches:
      - master
    paths:
      - components/*
      - pages/*
      - package.json
      - next.config.js

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.9.1]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install npm and test
        run: |
          npm install
          npm tslint
          npm test
        env:
          CI: true
